version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aiplanet
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon_submission
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - my-network

  api:
    build: .
    command: sh -c "python hackathon_submission/manage.py migrate && python hackathon_submission/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./hackathon_submission:/code/hackathon_submission
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: aiplanet
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon_submission
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network:
